#!/bin/bash

cleanup() {
    echo "Terminating all Python scripts..."
    # 终止所有子进程
    pkill -P $$
    exit 1
}
trap cleanup SIGINT SIGTERM

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BACE" --run_name "BACE-from-HIV-003"          --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BACE" --run_name "BACE-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "BACE" --run_name "BACE-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BACE" --run_name "BACE-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BACE" --run_name "BACE-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "BACE" --run_name "BACE-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BACE" --run_name "BACE-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BACE" --run_name "BACE-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "BACE" --run_name "BACE-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BACE" --run_name "BACE-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BACE" --run_name "BACE-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-MUV-003"          --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "BBBP" --run_name "BBBP-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ClinTox" --run_name "ClinTox-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "SIDER" --run_name "SIDER-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Tox21" --run_name "Tox21-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ToxCast" --run_name "ToxCast-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "ESOL" --run_name "ESOL-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "FreeSolv" --run_name "FreeSolv-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"             --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"                   --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"           --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "Lipophilicity" --run_name "Lipophilicity-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt" --seed 888 --num-epochs 200 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait


CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "HIV" --run_name "HIV-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                   --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "HIV" --run_name "HIV-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                     --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "HIV" --run_name "HIV-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                    --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "HIV" --run_name "HIV-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"                   --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "HIV" --run_name "HIV-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"             --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "HIV" --run_name "HIV-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "HIV" --run_name "HIV-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"                 --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "HIV" --run_name "HIV-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"             --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "HIV" --run_name "HIV-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "HIV" --run_name "HIV-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "HIV" --run_name "HIV-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 50 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait

CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "MUV" --run_name "MUV-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                   --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "MUV" --run_name "MUV-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "MUV" --run_name "MUV-from-PCBA-003"         --load_ckpt_path "./log/pretrain-PCBA-001/PCBA_model.pt"                    --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "MUV" --run_name "MUV-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"                   --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "MUV" --run_name "MUV-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"             --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "MUV" --run_name "MUV-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "MUV" --run_name "MUV-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"                 --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "MUV" --run_name "MUV-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"             --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "MUV" --run_name "MUV-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"                   --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "MUV" --run_name "MUV-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt"           --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "MUV" --run_name "MUV-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt" --seed 888 --num-epochs 20 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait


CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-BACE-003"          --load_ckpt_path "./log/pretrain-BACE-001/BACE_model.pt"                     --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-HIV-003"           --load_ckpt_path "./log/pretrain-HIV-001/HIV_model.pt"                     --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-Lipophilicity-003" --load_ckpt_path "./log/pretrain-Lipophilicity-001/Lipophilicity_model.pt"                   --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-MUV-003"           --load_ckpt_path "./log/pretrain-MUV-001/MUV_model.pt"                   --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-BBBP-003"          --load_ckpt_path "./log/pretrain-BBBP-001/BBBP_model.pt"             --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-ClinTox-003"       --load_ckpt_path "./log/pretrain-ClinTox-001/ClinTox_model.pt"                 --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-SIDER-003"         --load_ckpt_path "./log/pretrain-SIDER-001/SIDER_model.pt"                 --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-Tox21-003"         --load_ckpt_path "./log/pretrain-Tox21-001/Tox21_model.pt"             --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=3 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-ToxCast-003"       --load_ckpt_path "./log/pretrain-ToxCast-001/ToxCast_model.pt"                   --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=1 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-ESOL-003"          --load_ckpt_path "./log/pretrain-ESOL-001/ESOL_model.pt"           --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
CUDA_VISIBLE_DEVICES=2 python src/finetune.py --dataset "PCBA" --run_name "PCBA-from-FreeSolv-003"      --load_ckpt_path "./log/pretrain-FreeSolv-001/FreeSolv_model.pt" --seed 888 --num-epochs 10 --batch_size 32 --learning_rate 0.001 --save_ckpt_step 1 --log_path ./log --split scaffold --split-ratio "0.8,0.1,0.1" --num-workers 0 --wandb &
wait


echo "All Python scripts have finished."